### ISSUE TITLE
OpenSRP and OpenMRS sync integration does not create a patient

### ISSUE THREAD

**Issue by hmakandi** [OpenSRP/opensrp-server-web#118]
OpenSRP and OpenMRS sync integration does not create a patient. It was noted that OpenSRP sends the request to create a person, and attempts to create a patient without the person uuid created in the previous call. This causes a loop where it in OpenMRS where it creates multiple persons because the person id is not created, and does not create the patient anyways.

**Comment by hmakandi** [comment]
@Andati please add more info to this issue

**Comment by Andati** [comment]
Below is the error that is shown in OpenSP error log

`https://openmrs.boresha-afya-stage.smartregister.org/openmrs/ws/rest/v1/person
{"birthdateEstimated":false,"addresses":[{"address6":"","cityVillage":"Mabila"}],"birthdate":"1970-01-01","names":[{"givenName":"Kagodoro","familyName":"Family","middleName":""}],"gender":"Male"}
https://openmrs.boresha-afya-stage.smartregister.org/openmrs/ws/rest/v1/patientidentifiertype/opensrp_id?v=custom:(uuid)
https://openmrs.boresha-afya-stage.smartregister.org/openmrs/ws/rest/v1/patientidentifiertype/OpenSRP%20Thrive%20UID?v=custom:(uuid)
https://openmrs.boresha-afya-stage.smartregister.org/openmrs/ws/rest/v1/patient
{"person":"cc226563-cdc6-4c3b-81fd-403b48c4b06c","identifiers":[{"identifier":"4057501_famil-y","location":"Unknown Location","identifierType":"fd3b40ed-d184-48e8-8b2a-71e40f20b9bf"},{"identifier":"6e53c875-15fd-4256-beef-ae6502fe2f89","location":"Unknown Location","identifierType":"7015edcd-6624-4f81-b236-c2c1117223b6","preferred":true}]}
[REPORT] 12092019 09:20:04,812 ERROR [applicationScheduler-8] [OpenmrsSyncerListener]
org.json.JSONException: JSONObject["uuid"] not found.
        at org.json.JSONObject.get(JSONObject.java:499)
        at org.json.JSONObject.getString(JSONObject.java:670)
        at org.opensrp.connector.openmrs.service.PatientService.processClients(PatientService.java:373)
        at org.opensrp.connector.openmrs.schedule.OpenmrsSyncerListener.pushClient(OpenmrsSyncerListener.java:133)
        at org.opensrp.connector.openmrs.schedule.OpenmrsSyncerListener.pushToOpenMRS(OpenmrsSyncerListener.java:100)
        at sun.reflect.GeneratedMethodAccessor261.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:64)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:53)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[REPORT] 12092019 09:20:04,812 DEBUG [applicationScheduler-8] [insertSelective] ==>  Preparing: insert into error.error_trace ( document_id, date_occurred, error_type, stack_trace, record_id, document_type, retry_url ) values ( ?, ?, ?, ?, ?, ?, ? )
[REPORT] 12092019 09:20:04,812 DEBUG [applicationScheduler-8] [insertSelective] ==> Parameters: 94cb7c9b-432e-4862-ba2c-8b1095a9bfb3(String), 2019-09-12 09:20:04.812(Timestamp), OPENMRS FAILED CLIENT PUSH(String), org.json.JSONException: JSONObject["uuid"] not found.
        at org.json.JSONObject.get(JSONObject.java:499)
        at org.json.JSONObject.getString(JSONObject.java:670)
        at org.opensrp.connector.openmrs.service.PatientService.processClients(PatientService.java:373)
        at org.opensrp.connector.openmrs.schedule.OpenmrsSyncerListener.pushClient(OpenmrsSyncerListener.java:133)
        at org.opensrp.connector.openmrs.schedule.OpenmrsSyncerListener.pushToOpenMRS(OpenmrsSyncerListener.java:100)
        at sun.reflect.GeneratedMethodAccessor261.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:64)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:53)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
(String), 6e53c875-15fd-4256-beef-ae6502fe2f89(String), org.opensrp.domain.Client(String), (String)
`
