### ISSUE TITLE
Export event data write CSV on temp directory

### ISSUE THREAD

**Issue by rehammuzzamil** [OpenSRP/opensrp-server-web#736]
- The problem of access denied is occurring in the stage servers. 
- The solution is to write a file to the tmp directory.

Currently, on production servers getting following stack trace:
```
IO Exception occurred caroly
n's_feb_23_mission_fix_problem_2021-02-24.csv
java.nio.file.AccessDeniedException: carolyn's_feb_23_mission_fix_problem_2021-02-24.csv
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:220)
        at java.base/java.nio.file.Files.newBufferedWriter(Files.java:2920)
        at java.base/java.nio.file.Files.newBufferedWriter(Files.java:2963)
        at org.opensrp.web.rest.EventResource.generateCSV(EventResource.java:740)
        at org.opensrp.web.rest.EventResource.exportEventData(EventResource.java:631)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:
62)
```

**Comment by rehammuzzamil** [comment]
I have done a fix for Access Denied Exceptions, and the PR is in the review phase https://github.com/OpenSRP/opensrp-server-web/pull/739, but I have a question. Can we deploy a preview version on stage for the sake of testing purposes? @Samuel Githengi @carolyn @Benn Simon

**Comment by rehammuzzamil** [comment]
I have tried out multiple solutions to resolve this AccessDenied Exception. Here is the summary:

- Tried using `File.createTempFile(prefix, suffix) ` for generating CSV files, but there is a problem in this approach, CSV files are being written along with the complete temp path like `opt/tomcat..` which is not correct.
- I have tried out another solution based on this commit https://github.com/OpenSRP/opensrp-server-web/pull/739/commits/da31b46137284f6503515f137df6c8366d836fe9, it worked fine on local but deploying on stage server resulted in throwing the same exception.
- This morning, I have tried out another solution to create CSV files inside the zip file. The zip file is created in the temp folder, but it is again throwing the same exception on the Stage server.

 @githengi Can you please help me figure this out, as it works fine in my local environment? 
Thanks to @bennsimon for deploying this issue's branch for me on the staging server.

cc: @cafootitt

**Comment by githengi** [comment]
@rehammuzzamil where is the temp files being created? also which OS and JVM are you using?

**Comment by rehammuzzamil** [comment]
> @rehammuzzamil where is the temp files being created? also which OS and JVM are you using?

Using `System.getProperty("java.io.tmpdir");` for tempDirectory. It is being created in` /opt/tomcat/apache-tomcat-9.0.41/temp`. I am using Ubuntu locally. @githengi

**Comment by rehammuzzamil** [comment]
Hi @githengi Do you have any suggestions/ideas to fix this issue?
