### ISSUE TITLE
Fix  IllegalArgument exception thrown during plan evaluation

### ISSUE THREAD

**Issue by Rkareko** [OpenSRP/opensrp-server-web#761]
The following error is being thrown on Reveal stage during plan evaluation

``
[REPORT] 26022021 06:38:14,458 ERROR [listener-1] [RabbitMQConfig$MyFatalExceptionStrategy] Failed to process inbound message from queue rabbitmq.task.queue; failed message: (Body:'{"planIdentifier":"4f63fa7a-75fe-5072-972d-0fd849f75110","triggerType":"PLAN_ACTIVATION","jurisdiction":{"code":"ea15a719-afbb-4016-a97c-b793848ca150"},"username":"superset-user"}' MessageProperties [headers={__TypeId__=org.opensrp.queue.PlanEvaluatorMessage}, contentType=application/json, contentEncoding=UTF-8, contentLength=0, receivedDeliveryMode=PERSISTENT, priority=0, redelivered=true, receivedExchange=, receivedRoutingKey=rabbitmq.task.queue, deliveryTag=9536059, consumerTag=amq.ctag-DZ2yUnSp9XfSj_NN01nvsg, consumerQueue=rabbitmq.task.queue])
org.springframework.amqp.rabbit.support.ListenerExecutionFailedException: Listener method 'public void org.opensrp.queue.RabbitMQReceiver.receiver(org.opensrp.queue.PlanEvaluatorMessage)' threw exception
	at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:228)
	at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.invokeHandlerAndProcessResult(MessagingMessageListenerAdapter.java:148)
	at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:133)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1591)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1510)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1498)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:1489)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1433)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:970)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:916)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1600(SimpleMessageListenerContainer.java:83)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.mainLoop(SimpleMessageListenerContainer.java:1291)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1197)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: not_eligible
	at com.ibm.fhir.model.type.code.LocationStatus$ValueSet.from(LocationStatus.java:188)
	at com.ibm.fhir.model.type.code.LocationStatus$Builder.value(LocationStatus.java:137)
	at org.smartregister.converters.LocationConverter.convertPhysicalLocationToLocationResource(LocationConverter.java:34)
	at org.opensrp.repository.postgres.LocationRepositoryImpl.lambda$convertToFHIRLocation$0(LocationRepositoryImpl.java:948)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.opensrp.repository.postgres.LocationRepositoryImpl.convertToFHIRLocation(LocationRepositoryImpl.java:949)
	at org.opensrp.repository.postgres.LocationRepositoryImpl.findLocationByJurisdiction(LocationRepositoryImpl.java:939)
	at jdk.internal.reflect.GeneratedMethodAccessor164.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:205)
	at com.sun.proxy.$Proxy64.findLocationByJurisdiction(Unknown Source)
	at org.smartregister.pathevaluator.action.ActionHelper.getSubjectResources(ActionHelper.java:72)
	at org.smartregister.pathevaluator.plan.PlanEvaluator.lambda$evaluatePlan$3(PlanEvaluator.java:119)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.smartregister.pathevaluator.plan.PlanEvaluator.evaluatePlan(PlanEvaluator.java:112)
	at org.opensrp.queue.RabbitMQReceiver.receiver(RabbitMQReceiver.java:61)
	at jdk.internal.reflect.GeneratedMethodAccessor163.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:171)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:120)
	at org.springframework.amqp.rabbit.listener.adapter.DelegatingInvocableHandler.invoke(DelegatingInvocableHandler.java:130)
	at org.springframework.amqp.rabbit.listener.adapter.HandlerAdapter.invoke(HandlerAdapter.java:66)
	at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:220)
	... 13 more

```

**Comment by rehammuzzamil** [comment]
Hi @Rkareko, Does this issue exists against all Reveal plans?
If yes, can you please share a sample plan, therefore, I can test it on my local? Thanks.

cc : @githengi

**Comment by Rkareko** [comment]
@rehammuzzamil This is happening on `v2.4.28-SNAPSHOT` of Opensrp

**Comment by Rkareko** [comment]
@rehammuzzamil  here is a sample plan https://reveal-stage.smartregister.org/opensrp/rest/plans/4f63fa7a-75fe-5072-972d-0fd849f75110

`[{"identifier":"4f63fa7a-75fe-5072-972d-0fd849f75110","version":"1","name":"Dynamic-MDA-2021-02-24","title":"SMC Nigeria test 2021","status":"active","date":"2021-02-24","effectivePeriod":{"start":"2021-02-24","end":"2021-03-16"},"useContext":[{"code":"interventionType","valueCodableConcept":"Dynamic-MDA"},{"code":"taskGenerationStatus","valueCodableConcept":"internal"}],"jurisdiction":[{"code":"12eaba32-55bb-4a67-b554-a28d9ab8e02a"}],"serverVersion":1599112764883,"goal":[{"id":"RACD_register_families","description":"Register all families \u0026amp; family members in all residential structures enumerated (100%) within the operational area","priority":"medium-priority","target":[{"measure":"Percent of residential structures with full family registration","detail":{"detailQuantity":{"value":100.0,"comparator":"\u0026gt;\u003d","unit":"Percent"}},"due":"2021-03-03"}]},{"id":"MDA_Dispense","description":"Visit all residential structures (100%) dispense prophylaxis to each registered person","priority":"medium-priority","target":[{"measure":"Percent of Registered person(s)","detail":{"detailQuantity":{"value":75.0,"comparator":"\u0026gt;\u003d","unit":"Percent"}},"due":"2021-03-03"}]},{"id":"MDA_Adherence","description":"Visit all residential structures (100%) and confirm adherence of each registered person","priority":"medium-priority","target":[{"measure":"Percent of dispense recipients","detail":{"detailQuantity":{"value":100.0,"comparator":"\u0026gt;\u003d","unit":"Percent"}},"due":"2021-03-03"}]}],"action":[{"identifier":"8fc4344a-2ede-524d-becb-e81c71cddf81","prefix":1,"title":"Family Registration","description":"Register all families \u0026amp; family members in all residential structures enumerated (100%) within the operational area","code":"RACD Register Family","timingPeriod":{"start":"2021-02-24","end":"2021-03-03"},"reason":"Routine","goalId":"RACD_register_families","subjectCodableConcept":{"text":"Location"},"trigger":[{"type":"named-event","name":"plan-activation"},{"type":"named-event","name":"event-submission","expression":{"description":"Trigger when a Register_Structure event is submitted","expression":"questionnaire \u003d \u0027Register_Structure\u0027 or questionnaire \u003d \u0027Archive_Family\u0027"}}],"condition":[{"kind":"applicability","expression":{"description":"Structure is residential or type does not exist","expression":"$this.is(FHIR.QuestionnaireResponse) or (($this.type.where(id\u003d\u0027locationType\u0027).exists().not() or $this.type.where(id\u003d\u0027locationType\u0027).text \u003d \u0027Residential Structure\u0027) and $this.contained.exists().not())","subjectCodableConcept":{"text":"Family"}}},{"kind":"applicability","expression":{"description":"Apply to residential structures in Register_Structure questionnaires","expression":"$this.is(FHIR.Location) or (questionnaire \u003d \u0027Register_Structure\u0027 and $this.item.where(linkId\u003d\u0027structureType\u0027).answer.value \u003d\u0027Residential Structure\u0027)"}}],"definitionUri":"family_register.json","type":"create"},{"identifier":"c6856fe1-3503-5d9d-a2e4-86f226230487","prefix":2,"title":"Distribute Drugs","description":"Visit all residential structures (100%) and dispense prophylaxis to each registered person","code":"MDA Dispense","timingPeriod":{"start":"2021-02-24","end":"2021-03-03"},"reason":"Routine","goalId":"MDA_Dispense","subjectCodableConcept":{"text":"Person"},"trigger":[{"type":"named-event","name":"plan-activation"},{"type":"named-event","name":"event-submission","expression":{"description":"Trigger when a Family Registration or Family Member Registration event is submitted","expression":"questionnaire \u003d \u0027Family_Registration\u0027 or questionnaire \u003d \u0027Family_Member_Registration\u0027"}}],"condition":[{"kind":"applicability","expression":{"description":"Person or person associated with questionaire response is older than 5 years and younger than 15 years","expression":"($this.is(FHIR.Patient) and $this.birthDate \u0026lt;\u003d today() - 5 \u0027years\u0027 and $this.birthDate \u0026gt; today() - 15 \u0027years\u0027) or ($this.contained.where(Patient.birthDate \u0026lt;\u003d today() - 5 \u0027years\u0027 and $this.birthDate \u0026gt; today() - 15 \u0027years\u0027).exists())"}}],"definitionUri":"mda_dispense.json","type":"create"},{"identifier":"643af24a-cda6-5fc3-a77f-1261edf08a45","prefix":3,"title":"MDA Adherence","description":"Visit all residential structures (100%) and confirm adherence of each registered person","code":"MDA Adherence","timingPeriod":{"start":"2021-02-24","end":"2021-03-03"},"reason":"Routine","goalId":"MDA_Adherence","subjectCodableConcept":{"text":"Person"},"trigger":[{"type":"named-event","name":"event-submission","expression":{"description":"Trigger when a MDA Dispense event is submitted","expression":"questionnaire \u003d \u0027mda_dispense\u0027"}}],"condition":[{"kind":"applicability","expression":{"description":"The person fully received the dispense activity","expression":"$this.item.where(linkId\u003d\u0027business_status\u0027).answer.value \u003d \u0027Fully Received\u0027"}}],"definitionUri":"mda_adherence.json","type":"create"}],"experimental":false}]`

**Comment by Rkareko** [comment]
@rehammuzzamil this is still happening in tha latest snapshot `v2.4.36-SNAPSHOT`

**Comment by rehammuzzamil** [comment]
@Rkareko Thanks for sharing the plan definition. I tried replicating the issue but it did not work on my end. Maybe there are some pre-requisite steps to actually generate a task. Though, both the listener functions were invoked of the `RabbitMQListener` class, and no exception was noted in the logs of the local environment.
cc: @githengi

**Comment by Rkareko** [comment]
@rehammuzzamil find the db dump for reveal stage [here](https://drive.google.com/file/d/1Zvxn7gOkoIkK-kkmUVC6OvcnH_xMXbkB/view?usp=sharing) . 

Could you use this to reproduce the issue. Also note that this happens when RabbitMq is running

**Comment by rehammuzzamil** [comment]
> @rehammuzzamil find the db dump for reveal stage [here](https://drive.google.com/file/d/1Zvxn7gOkoIkK-kkmUVC6OvcnH_xMXbkB/view?usp=sharing) .
> 
> Could you use this to reproduce the issue. Also note that this happens when RabbitMq is running

Sure, I will try with the payload shared above for the plan using the reveal stage DB. 
@Rkareko  I have requested the access.

**Comment by Rkareko** [comment]
@rehammuzzamil granted access

**Comment by Rkareko** [comment]
@rehammuzzamil looking at the exception shared above it occurs the issues appear when converting the [NOT_ELIGIBLE](https://github.com/OpenSRP/opensrp-plan-evaluator/blob/master/src/main/java/org/smartregister/domain/LocationProperty.java#L22)  Location status [here](https://github.com/OpenSRP/opensrp-plan-evaluator/blob/master/src/main/java/org/smartregister/converters/LocationConverter.java#L34) . 

The not_eligible status is not found in the ibm fhir model [LocationStatus values](https://github.com/IBM/FHIR/blob/main/fhir-model/src/main/java/com/ibm/fhir/model/type/code/LocationStatus.java#L56-L67)  

Could you verify whether this analysis is correct

**Comment by githengi** [comment]
@rehammuzzamil Please map Location status Not Eligible to Suspended in https://github.com/OpenSRP/opensrp-plan-evaluator/blob/master/src/main/java/org/smartregister/converters/LocationConverter.java#L30:L32

That seem to be causing the issue

**Comment by rehammuzzamil** [comment]
> @rehammuzzamil Please map Location status Not Eligible to Suspended in https://github.com/OpenSRP/opensrp-plan-evaluator/blob/master/src/main/java/org/smartregister/converters/LocationConverter.java#L30:L32
> 
> That seem to be causing the issue

Sure @githengi @Rkareko looking into this.

**Comment by rehammuzzamil** [comment]
> @rehammuzzamil looking at the exception shared above it occurs the issues appear when converting the [NOT_ELIGIBLE](https://github.com/OpenSRP/opensrp-plan-evaluator/blob/master/src/main/java/org/smartregister/domain/LocationProperty.java#L22) Location status [here](https://github.com/OpenSRP/opensrp-plan-evaluator/blob/master/src/main/java/org/smartregister/converters/LocationConverter.java#L34) .
> 
> The not_eligible status is not found in the ibm fhir model [LocationStatus values](https://github.com/IBM/FHIR/blob/main/fhir-model/src/main/java/com/ibm/fhir/model/type/code/LocationStatus.java#L56-L67)
> 
> Could you verify whether this analysis is correct

Yes this is correct.

**Comment by Rkareko** [comment]
@rehammuzzamil is there a web snapshot for the fix?

**Comment by rehammuzzamil** [comment]
@Rkareko  waiting for this to be published https://github.com/OpenSRP/opensrp-plan-evaluator/releases/tag/v1.4.1-SNAPSHOT
Once published, I will create a PR for core and then server web.

**Comment by rehammuzzamil** [comment]
@Rkareko Could you please publish the above release tag for plan-evaluator?

**Comment by Rkareko** [comment]
@rehammuzzamil the plan-evaluator snapshot has been published
